#!/usr/bin/zsh

LC_ALL=C
HOSTNAME=`hostname`
if [ -d $HOME/.keychain ]; then
    if [ -f $HOME/.ssh/id_dsa ]; then
        keychain $HOME/.ssh/id_dsa
    elif [ -f $HOME/.ssh/id_rsa ]; then
        keychain $HOME/.ssh/id_rsa
    fi
    source $HOME/.keychain/*-sh
fi

export PATH=/usr/local/git/bin:$PATH

if [ -f /sw/bin/init.sh ]; then
    source /sw/bin/init.sh
fi

export ST_VE_NAME=dev10
