#!/usr/bin/zsh

LC_ALL=C
HOSTNAME=`hostname`
if [ -d $HOME/.keychain ]; then
    if [ -f $HOME/.ssh/id_dsa ]; then
        keychain $HOME/.ssh/id_dsa
    elif [ -f $HOME/.ssh/id_rsa ]; then
        keychain $HOME/.ssh/id_rsa
    fi
    source $HOME/.keychain/*-sh
fi

if [ -d /usr/local/git/bin ]; then
    export PATH=/usr/local/git/bin:$PATH
fi


if [ -f /sw/bin/init.sh ]; then
    source /sw/bin/init.sh
fi

if [ -d /opt/local/bin ]; then
    export PATH=/opt/local/bin:/opt/local/sbin:$PATH
fi

if [ -f $HOME/Android ]; then
    export ANDROID_SWT=$HOME/Android/sdk/tools/lib/x86
    export PATH=$HOME/Android/sdk/tools:$PATH
fi
export ST_VE_NAME=dev10
export TEST_LESS_VERBOSE=1
