#!/bin/bash

# functions and aliases for dev env and appliance

    alias walltime='ps -eo pid,etime | grep '
    alias releaseme="export ST_APT=apt.socialtext.net"
    alias unreleaseme="unset ST_APT"
    alias benchme="st-config set benchmark_mode 1"
    alias grnok="grep  -C 6 'not ok' testcases.out"
    alias grnokk="grep 'not ok' testcases.out"
    alias grtc="grep 'Loading test plan\|COMPLETED' testcases.out"
    alias ttc='tail -f testcases.out'

if [ -e /etc/socialtext/socialtext.conf ]; then

   # aliases for an appliance
    alias sww='sudo -u www-data '
    alias swa='sudo -u www-data st-admin '
    alias cdwt='cd /usr/share/nlw/workspaces/wikitests'
    alias cdappwt='cd /usr/share/stconfig/stbin/qa/appliance'
    alias findwikis='ls /var/www/socialtext/data/'
    alias restartme='sudo /etc/init.d/apache2 stop; sudo /etc/init.d/apache-perl stop; sleep 5; sudo /etc/init.d/apache-perl start; sudo /etc/init.d/apache2  start;'
    alias ceqread='/usr/bin/ceq-read'
    alias ceqstat='/usr/bin/ceq-stat'
    alias ceqrm='/usr/bin/ceq-rm'
    alias cdskin='cd /usr/share/nlw/skin'
    alias cdplugins='cd /usr/share/nlw/plugins'
    alias noplugins='sudo /etc/init.d/apache-perl stop; sudo apt-get remove --purge  socialtext-plugin-people socialtext-plugin-gadgets; sudo /etc/init.d/apache-perl start'

    SETSEL='/usr/share/stconfig/stbin/qa/appliance/setup-selenium'
    alias setsel="source $SETSEL"

    RWT='/usr/share/stconfig/stbin/run-wiki-tests'

    alias xwt='export ST_SKIN_NAME='\''s3'\''; export WIKIEMAIL=$HOSTNAME; sudo -u www-data $RWT --no-maximize --test-username wikitester@ken.socialtext.net  --test-email wikitester@ken.socialtext.net --timeout 60000 --plan-server http://$HOSTNAME --test-server http://$HOSTNAME --plan-page  '

    alias xlwt='export ST_SKIN_NAME='\''s3'\''; export WIKIEMAIL=$HOSTNAME; sudo -u www-data $RWT  --no-maximize --test-username devnullx --test-password ldapd3v  --test-email devnullx@socialtext.com  --timeout 60000 --plan-server http://$HOSTNAME --test-server http://$HOSTNAME  0 --plan-page  '

    tapout() {
        st-tap2html $1.out
        sudo cp $1.html /usr/share/nlw/
    }

else

    # aliases for a dev env
    alias pdel='$ST_CURRENT/socialtext-reports/parse-dev-env-logs'
    alias gunp='pushd $ST_CURRENT; st-git-all \@fetch;gunpulledall; popd'
    alias sta='$ST_CURRENT/nlw/bin/st-admin '
    alias makeme='$ST_CURRENT/nlw/dev-bin/st-make-js; restartme;'
    alias freshdev='~/personal/qa/tests-to-tarballs.bash; $ST_CURRENT/nlw/dev-bin/fresh-dev-env-from-scratch; $ST_CURRENT/nlw/bin/ceq-rm Index; $ST_CURRENT/nlw/bin/st-config set benchmark_mode 1'
    alias tests-from-tarballs='~/personal/qa/tests-from-tarballs.bash'
    alias tests-to-tarballs='~/personal/qa/tests-to-tarballs.bash'
    alias stopme='$ST_CURRENT/nlw/dev-bin/nlwctl stop'
    alias startme='$ST_CURRENT/nlw/dev-bin/nlwctl start'
    alias restartme='$ST_CURRENT/nlw/dev-bin/nlwctl restart'
    alias ceqread='$ST_CURRENT/nlw/bin/ceq-read'
    alias ceqstat='$ST_CURRENT/nlw/bin/ceq-stat'
    alias ceqrm='$ST_CURRENT/nlw/bin/ceq-rm'
    alias findceq='ps x  | grep ceqlotron | grep -v grep'
    alias findwikis='ls ~/.nlw/root/data/'

    alias cdfix='cd $ST_CURRENT/nlw/lib/Socialtext/WikiFixture'
    alias cdroot='cd ~/.nlw/root'
    alias cddata='cd ~/.nlw/root/data'
    alias cdetc='cd ~/.nlw/etc'
    alias cdconf='cd ~/.nlw/etc/socialtext'
    alias cdlog='cd ~/.nlw/log'
    alias cdfonts='cd $ST_CURRENT/nlw/share/fonts'
    alias cdwidgets='cd $ST_CURRENT/nlw/share/widgets'
    alias cdpers='cd ~/personal'
    alias cdqa='cd ~/personal/qa'
    alias cdstbin='cd ~/stbin'
    alias cdappwt='cd ~/stbin/qa/appliance'
    alias cdwt='cd $ST_CURRENT/nlw/share/workspaces/wikitests'
    alias cdst='cd $ST_SRC_BASE'
    alias cdshare='cd $ST_CURRENT/nlw/share'
    alias cdhelp='cd $ST_CURRENT/nlw/share/l10n/help'
    alias cdndb='cd $ST_CURRENT/nlw/dev-bin'
    alias cdnb='cd $ST_CURRENT/nlw/bin'
    
    # aliases to run wikitests
    RWT=$ST_SRC_BASE/stconfig/personal/qa/run-wiki-tests.bash

    alias rwt="export ST_SKIN_NAME='s3'; $RWT $1 $2 $3"
    alias xwt="export ST_SKIN_NAME='s3'; run-wiki-tests --no-maximize --test-username wikitester@ken.socialtext.net  --test-email wikitester@ken.socialtext.net --timeout 60000 --plan-page  "
    alias xlwt="export ST_SKIN_NAME='s3'; run-wiki-tests --no-maximize --test-username devnullx --test-password ldapd3v  --test-email devnullx@socialtext.com  --timeout 60000 --plan-page  "

    SETSEL=$ST_SRC_BASE/stconfig/personal/qa/setup-selenium
    alias setsel="source $SETSEL"

    # aliases to find out what's running
    alias psqa1='ps -u qa1 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa2='ps -u qa2 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa3='ps -u qa3 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa4='ps -u qa4 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa5='ps -u qa5 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa6='ps -u qa6 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa7='ps -u qa7 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa8='ps -u qa8 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa9='ps -u qa9 -f | grep -E -v bash\|ssh\|ps\|screen'

    alias psqa10='ps -u qa10 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa11='ps -u qa11 -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psqa12='ps -u qa12 -f | grep -E -v bash\|ssh\|ps\|screen'

    alias pssel='ps -u selenium -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psken='ps -u kenpier -f | grep -E -v bash\|ssh\|ps\|screen'
    alias psmatt='ps -u mheusser -f | grep -E -v bash\|ssh\|ps\|screen'

    # functions

    tapout() {
        st-tap2html $1.out
        cp $1.html $ST_CURRENT/nlw/share/
    }

    branches() { 
        WDD=$PWD
        for i in `cat $ST_SRC_BASE/stconfig/personal/qa/qausers` ; do
            echo $i;
            cd /home/$i/src/st/current;
            git branch | grep "*";
        done;
        cd $WDD
    }
    
    sb()        { set-branch $1; cdnlw; cd ..; }

    alias brqa='branches'
    alias ffx='ps auxww | grep firefox'
    alias fsel='ps auxww | grep selenium'

    if [ -e /etc/bash_completion.d/socialtext ]; then
        source /etc/bash_completion.d/socialtext 
    fi

    # git prompt
    COLOR_BRANCH=""
    COLOR_REPO=""
    COLOR_WORKDIR=""
    export PROMPT_COMMAND=_git_prompt_color

fi

    xwtt() {
        xwt $1 >& $1.out &
        ln -sf $1.out testcases.out
    }

    xlwtt() {
        xlwt $1 >& $1.out &
        ln -sf $1.out testcases.out
    }

