#!/bin/bash
# @COPYRIGHT@

# uncomment first line of sources.list to get ubuntu dependencies for slapd
sudo perl -pi -e 's/^#\s+deb http/deb http/' /etc/apt/sources.list
sudo apt-get update

ACC=$1
[ $ACC ] || ACC=$HOSTNAME
DA=`sudo st-admin get-default-account | grep  -o $ACC`

echo ""
if [ "$DA"  != '' ]; then
    echo DEFAULT ACCOUNT MATCHES  $ACC
else
    echo  `sudo st-admin get-default-account`
    echo "The default account should be the hostname, $HOSTNAME"
    echo "USE st-appliance-wikitests DEFAULT_ACCOUNT to specify default account.  Exiting"
    exit 1
fi
echo ""

WIKITESTS="/usr/share/stconfig/stbin/qa/appliance"

echo "Installing additional packages"
sudo apt-get install --yes libtest-harness-perl
sudo apt-get install --yes libaccessors-perl
sudo apt-get install --yes libtap-formatter-html-perl
sudo apt-get install --yes libtest-http-perl
sudo apt-get install --yes libtest-differences-perl

echo INSTALLING and ENABLING all plugins for all accounts
sudo st-appliance-install-plugin dashboard people socialcalc signals groups
sudo st-admin enable-plugin --all-accounts --plugin dashboard
sudo st-admin enable-plugin --all-accounts --plugin signals
sudo st-admin enable-plugin --all-accounts --plugin groups

echo INSTALLING wikitest_files
if [ ! -e /opt/wikitest_files ]; then
    sudo mkdir /opt/wikitest_files
fi
sudo unzip -u $WIKITESTS/wikitestfiles.zip  -d /opt/wikitest_files/

if [ -e /var/www/socialtext/data/test-data ]; then
    echo "DELETING old test-data workspace"
    sudo st-admin delete-workspace --w test-data  --no-export
fi
echo "IMPORTING  test-data  WORKSPACE"
sudo st-admin import-workspace --tarball $WIKITESTS/test-data.tar.gz
sudo st-admin set-workspace-config --w test-data account_name $ACC || true
sudo st-admin enable-plugin --p socialcalc --w test-data

if [ -e /var/www/socialtext/data/wikitests ]; then
    echo "DELETING old wikitests workspace"
    sudo st-admin delete-workspace --w wikitests --no-export
fi

echo "IMPORTING wikitests WORKSPACE"
sudo apt-get install --yes st-static-files-wikitests
sudo ln -sf $WIKITESTS/fast-import-pages  /usr/bin/
sudo $WIKITESTS/appliancetests-to-wiki
sudo st-admin set-workspace-config --w wikitests account_name $ACC || true

echo "SETTING user accounts to $ACC, which is supposed to be the default account"
sudo st-admin set-user-account --e wikitester@ken.socialtext.net --account $ACC
sudo st-admin set-user-account --e devnull1@socialtext.com --account $ACC

echo "GRANTING Accounts and System admin to devnull1"
sudo st-admin give-system-admin --e devnull1@socialtext.com
sudo st-admin give-accounts-admin --e devnull1@socialtext.com

echo "INSTALLING slapd"
sudo apt-get install --yes slapd

# Make www-data own /etc/socialtext/ files so st-bootstrap-openldap will
# succeed from wikitests.
sudo chown -R www-data:www-data /etc/socialtext/
sudo chmod 666 /etc/socialtext/ldap.yaml

# link appliance wikitest files into the path
sudo ln -sf $WIKITESTS/st-bootstrap-openldap /usr/bin/
sudo ln -sf $WIKITESTS/st-appliance-socialcalc /usr/bin/
sudo ln -sf $WIKITESTS/st-appliance-wikitests  /usr/bin/
sudo ln -sf $WIKITESTS/st-consume-stub-reports /usr/bin/
sudo ln -sf $WIKITESTS/st-qa-growth-report-add-members /usr/bin/
sudo ln -sf $WIKITESTS/st-create-account-data /usr/bin/
sudo ln -sf $WIKITESTS/st-qa-growth-report-populate-db /usr/bin/
sudo ln -sf $WIKITESTS/st-populate-reports-db /usr/bin/
sudo ln -sf $WIKITESTS/reports-functions.pl /usr/bin/

sudo st-appliance-config set max_objects_for_control_panel 500

echo "Setting up /tmp/backup for Console Backup and Restore testing"
sudo mkdir -p /tmp/backup
sudo perl -pi -e "s#^local_archivedir: .+#local_archivedir: /tmp/backup#" /etc/socialtext/appliance.conf

echo "Preparing nlw log consumer"
sudo ln -sf /usr/bin/st-reports-consume-nlw-log /usr/sbin/st-appliance-reports-consume-nlw-log
sudo chmod 644 /var/log/nlw.log
sudo chmod 666 /var/cache/socialtext/logreader/*

echo "Enabling email"
sudo st-email enable

echo "NO LONGER POPULATING reports DB"
#echo "POPULATING reports DB"
#echo "CTRL-C to abort and finish wikitest installation"
#sudo st-populate-reports-db

echo "DONE"
