#!/bin/bash
set -e

if [ "$1" == "" ]; then
    echo Usage: "$0" DB_DUMP_FILE;
    exit 1;
fi

echo INSTALLING $1 database
sudo id
sudo st-appliance-ctl stop
sudo st-email disable
unset PGUSER
unset PGDATABASE
sudo st-db dropdb -s socialtext
sudo st-db createdb -s socialtext
sudo st-db escalate_privs
sudo psql -U nlw NLW -f $1 >/dev/null
sudo st-db revoke_privs
sudo st-email disable
sudo st-appliance-ctl start
sudo st-email disable
