#!/usr/bin/perl
use strict;
use warnings;

my $minutes = shift;
my $subject = shift || 'meeting';
die "USAGE: $0 <minutes> <subject>\n" unless $minutes;

my $user = $ENV{USER};
bob("$user is Starting a $subject $minutes minutes long");
while ($minutes > 0) {
    if (($minutes % 5) == 0) {
        bob("$minutes minutes left in $subject. ($user)");
    }
    sleep 60;
    $minutes--;
}
bob("Alert! $subject has reached alloted time. ($user)");
exit;

sub bob {
    my $msg = shift;
    system(qq{wget -q -O /dev/null "https://irc.socialtext.net:450/bob/$msg"});
}

