#!/bin/bash
set -x

cd ~
mkdir -p src/st
mkdir .ssh
cat - > .ssh/config <<EOT
Host github.com
	IdentityFile ~/.ssh/id_rsa_github
EOT

echo "In another window, copy .ssh/id_rsa_github from testrunner@galena"
read

# clone stconfig
cd src/st
git clone git@github.com:socialtext/stconfig.git

# clone stconfig
rm ~/.bashrc
rm ~/.bash_profile
rm ~/.zshrc
~/src/st/stconfig/stconfig-setup
. ~/.bashrc
~/stbin/git-std-cfg

cd ~/src/st
git clone git@github.com:socialtext/st-build-tools.git


# Socialtext repo is huge, so if we have a local copy then use it.
if [[ -d ~lukec/src/st/socialtext ]]; then
	cd ~/src/st
	git clone -l ~lukec/src/st/socialtext
	cp ~lukec/src/st/socialtext/.git/config socialtext/.git/config
fi

set-branch master

set +x
cat - <<EOM

Now run: . ~/.bashrc  or log-out/in

Run this as sudo on this box:
  sudo -u postgres createuser -d -s -r $USER
  sudo -u postgres psql $PGDATABASE -c "ALTER USER $USER SET search_path TO public,streports"

Then you can sb and fdefs on into the sunset

EOM
