#!/bin/zsh -ef

# USAGE myerrlogs [-1|-1a|-2|-2a|-p] [DIRECTORY]
#
#   -1      Only apache-perl error logs
#   -1a     Only apache-perl error and access logs
#   -2      Only apache2 error logs
#   -2a     Only apache2 error and access logs
#   -p      Only json-proxy log
#   -a      All access and error logs
#   DEFAULT All error logs
#
#   DIRECTORY defaults to ~/.nlw/log

dir=${2:-~/.nlw/log}

case "$1" in
    (-1)
        log="$dir/apache-perl/nlw-error*.log"
        ;;
    (-1a)
        log="$dir/apache-perl/*.log"
        ;;
    (-2)
        log="$dir/apache2/nlw-error*.log"
        ;;
    (-2a)
        log="$dir/apache2/*.log"
        ;;
    (-p)
        log="$dir/json-proxy.log"
        ;;
    (-a)
        log="$dir/*/*.log $dir/json-proxy.log"
        ;;
    (-n)
        log="$dir/nginx/*.log"
        ;;
    (*)
        log="$dir/*/nlw-error*.log $dir/json-proxy.log $dir/nginx/error.log"
        ;;
esac

eval exec colorizelogs $log
