#!/bin/zsh -ef

# USAGE myerrlogs [-1|-2] [DIRECTORY]
#
#   -1      Only apache-perl logs
#   -1e     Only apache-perl error logs
#   -2      Only apache2 logs
#   DEFAULT Everything
#
#   DIRECTORY defaults to ~/.nlw/log

logs=''

dir=${1:-~/.nlw/log}

case "$1" in
    (-1e)
        logs="$logs $dir/apache-perl/nlw-error*.log"
        shift
        ;;
    (-1)
        logs="$logs $dir/apache-perl/*.log"
        shift
        ;;
    (-2)
        logs="$logs $dir/apache2/*.log"
        shift
        ;;
    (-p)
        logs="$logs $dir/json-proxy.log"
        ;;
    (*)
        logs="$logs $dir/*/*.log $dir/json-proxy.log"
        ;;
esac

eval exec colorizelogs $logs
